RSA module
vk-lang-cpp/andeme pull request #6
Opened 2020-07-09 20:07 UTC by harashimahashi

#4

2020-07-10 07:19 UTC, nocomentsspb requested changes
Реализация методов должна быть гораздо сложнее.
При генерации ключей, надо:
-  из RSA структуры получить EVP_PKEY
- из EVP_PKEY взять публичный ключ и сохранить его например в PEM формате в string.
- с private аналогично

При проверке в обратном порядке.
Хороший пример на проверку и подпись https://gist.github.com/irbull/08339ddcd5686f509e9826964b17bb59

2020-07-10 07:19 UTC, nocomentsspb commented on common/keygen.h
> +		mutable std::string pubkey;
```suggestion
		const std::string public_key_;
```

see https://google.github.io/styleguide/cppguide.html#Variable_Names

В остальных местах аналогично

2020-07-10 07:19 UTC, nocomentsspb commented on common/keygen.h
> +		mutable std::string privkey;
Зачем тебе mutable тут? Лучше вообще const сделать

2020-07-10 07:19 UTC, nocomentsspb commented on common/keygen.h
> +		RSAUtil& operator=(RSAUtil&&) = delete;
По мне - излишне запрешать создание этого класса и удалять все конструкторы.
Какого-то функционального смысла это не несёт, а читаемость кода ухудшает.
Лучше убери.

2020-07-10 07:19 UTC, nocomentsspb commented on common/keygen.h
> +		static constexpr int size{ 4096 };
1) Плохое название. Не понятно чего это размер.
+ по Google Code Style должен быть префикс k
kSize
https://google.github.io/styleguide/cppguide.html#Constant_Names

2) Эту константу можно вынести внутрь .cpp в анонимный namespace.
Не вижу смысл высовывать её наружу компонента

2020-07-10 07:19 UTC, nocomentsspb commented on common/keygen.h
> +#define KEYGEN_H
Неправильно имя guard - см https://google.github.io/styleguide/cppguide.html#The__define_Guard

2020-07-10 07:19 UTC, nocomentsspb commented on common/keygen.h
> +		PublicKey(const std::string key) noexcept;
```suggestion
		PublicKey(const std::string& key);
```
Давай либо принимай по const std::string& либо уж через универсальную ссылку.
Но в обоих случаях noexcept не гарантируется

2020-07-15 17:27 UTC, nocomentsspb requested changes
1) Я так же предлагаю переименовать компонент из keygen в rsautil
Более консистентно получится.

2) Я замечания делал при первой встрече - надо аналогично ко всему коду применить

3) Напиши тест в keygen.t.cpp аналогичный моему с openssl - но используя RSAUtil, PublicKey и PrivateKey

2020-07-15 17:27 UTC, nocomentsspb commented on common/keygen.cpp
> +	std::string getPubKey(RSA* rsa) {
Согласно google code style - имена функций и методов с большой буквы
https://google.github.io/styleguide/cppguide.html#Function_Names

2020-07-15 17:27 UTC, nocomentsspb commented on common/keygen.cpp
> +		PEM_write_bio_RSAPublicKey(buf.get(), rsa);
Надо проверить код возрата - должен быть 1 в случае успеха.
Т.к. Google Code Style сильно не рекомендуется использовать исключения - можно обрабатывать ошибку, просто возвращая пустую строку.
И потом проверять, что строка не пустая

2020-07-15 17:27 UTC, nocomentsspb commented on common/keygen.cpp
> +		BIO_read(buf.get(), res.data(), length);
```suggestion
		BIO_read(buf.get(), res.data(), res.size());
```
Хотя res.size() == length, но более правильно использовать size() или length() методы.
Это убережёт от возможных ошибок и сделает код более понятны.
Мы передаём данные (res.data()) и их размер (res.size()) а не какое-то значение, не понятно как связанное с нашим объектом

2020-07-15 17:27 UTC, nocomentsspb commented on common/keygen.cpp
> +		res.resize(length);
```suggestion
		res.resize(BIO_ctrl_pending(buf.get()));
```

2020-07-15 17:27 UTC, nocomentsspb commented on common/keygen.cpp
> +		size_t length = BIO_ctrl_pending(buf.get());
```suggestion
```

2020-07-15 17:27 UTC, nocomentsspb commented on common/keygen.cpp
> +		BIO_read(buf.get(), res.data(), length);
Так же неплохо бы проверить, что res.size() == BIO_read 
Т.е. что всё прочитал

2020-07-15 17:27 UTC, nocomentsspb commented on common/keygen.cpp
> +		PEM_write_bio_RSAPrivateKey(buf.get(), rsa, nullptr, nullptr, 0, nullptr, nullptr);
Проверить код возврата

2020-07-15 17:27 UTC, nocomentsspb commented on common/keygen.cpp
> +	PublicKey::PublicKey(std::string&& key) noexcept : public_key_{ std::move(key) } {}
```suggestion
	PublicKey::PublicKey(std::string&& key) noexcept : public_key_(key) {}
```
У тебя есть конструктор принимающий универсальную ссылку
```c++
basic_string( basic_string&& other ) noexcept;
```

2020-07-15 17:27 UTC, nocomentsspb commented on common/keygen.cpp
> +		PEM_read_bio_RSAPublicKey(keybio.get(), &rsa_key, nullptr, nullptr);
```suggestion
		std::unique_ptr<RSA, decltype(&RSA_free)> rsa(
		    PEM_read_bio_RSAPublicKey(keybio.get(), nullptr, nullptr, nullptr),
		    RSA_free);
```
Можно все манипулации с pubKey и rsa_key свести в одну строчку.

2020-07-15 17:27 UTC, nocomentsspb commented on common/keygen.cpp
> +		res.resize(kKeySize / 8);
```suggestion
		res.resize(RSA_size(privKey.get()));
```
см https://www.openssl.org/docs/man1.1.0/man3/RSA_size.html

2020-07-15 17:27 UTC, nocomentsspb commented on common/keygen.h
> +		const std::string public_key_;
Тут можно убрать const (и у PrivateKey тоже)

2020-07-15 18:29 UTC, harashimahashi commented on common/keygen.cpp
> +	PublicKey::PublicKey(std::string&& key) noexcept : public_key_{ std::move(key) } {}
std::move нужен, семантика перемещения не передаётся – имя параметра key является l-значением

2020-07-16 15:32 UTC, nocomentsspb requested changes

2020-07-16 15:32 UTC, nocomentsspb commented on common/rsautil.t.cpp
> +    ASSERT_FALSE(pub1.Verify(priv1.Sign(test_data), test_data + "s"s));
Добавь ещё тест что подпись разными ключами разная.
+ добавь в ключе метод для получения значения ключа.
напримек const std::string& Value() const;
И проверь что у сгенерённых ключей разные Value()

2020-07-16 16:22 UTC, nocomentsspb approved these changes
LGTM

2020-07-16 16:24 UTC, merged